version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: yearly
    open-pull-requests-limit: 10
    assignees:
      - jonasscholl
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: yearly
    open-pull-requests-limit: 5
    assignees:
      - JonasScholl
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: yearly
    open-pull-requests-limit: 5
    assignees:
      - jonasscholl
    groups:
      composer:
        patterns:
          - "*"
