version: 2
updates:
  - package-ecosystem: npm
    directory: /tebuto-online-terminbuchung/block
    target-branch: main
    schedule:
      interval: monthly
    assignees:
      - jonasscholl
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - JonasScholl
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
