packages:
  - 'tebuto-online-terminbuchung/block'

overrides:
  '@opentelemetry/core': '^2.8.0'
  adm-zip: '^0.6.0'
  markdown-it: '^15.0.0'
  markdownlint-cli>minimatch: '^9.0.5'
  serialize-javascript: '^7.0.5'
  sockjs>uuid: '^11.1.1'

peerDependencyRules:
  allowedVersions:
    eslint: '*'
    'react-autosize-textarea>react': '*'
    'react-autosize-textarea>react-dom': '*'

allowBuilds:
  '@parcel/watcher': false
  core-js: false
  core-js-pure: false
  fsevents: false
  lefthook: true
  unrs-resolver: false
