sonar.projectKey=tebuto_wordpress-plugin_d85838b5-fae9-48e3-9636-0ec145a330f3

sonar.sources=tebuto-online-terminbuchung

sonar.exclusions=**/node_modules/**,**/block/build/**,**/.svn/**,**/assets-wporg/**,**/assets/**
